import type { Digest } from "@repomemory/contracts";

type DigestCardProps = {
  digest: Digest;
  selected: boolean;
  onSelect: (digestId: string) => void;
};

export function DigestCard({ digest, selected, onSelect }: DigestCardProps) {
  return (
    <button
      type="button"
      onClick={() => onSelect(digest.id)}
      className={`w-full rounded-xl border p-4 text-left transition ${
        selected ? "border-slate-900 bg-slate-900 text-white" : "border-slate-200 bg-white hover:border-slate-300"
      }`}
    >
      <p className={`text-xs uppercase tracking-[0.16em] ${selected ? "text-slate-200" : "text-slate-500"}`}>
        {new Date(digest.periodStart).toLocaleDateString()} - {new Date(digest.periodEnd).toLocaleDateString()}
      </p>
      <h3 className={`mt-2 text-lg font-semibold ${selected ? "text-white" : "text-slate-900"}`}>{digest.title}</h3>
      <p className={`mt-2 text-sm ${selected ? "text-slate-100" : "text-slate-600"}`}>{digest.summary}</p>
      <p className={`mt-3 text-xs ${selected ? "text-slate-200" : "text-slate-500"}`}>
        Generated by {digest.generatedBy} on {new Date(digest.createdAt).toLocaleString()}
      </p>
    </button>
  );
}
