import type { Digest } from "@repomemory/contracts";

type DigestDetailProps = {
  digest: Digest | null;
};

export function DigestDetail({ digest }: DigestDetailProps) {
  if (!digest) {
    return (
      <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h3 className="text-lg font-semibold text-slate-900">Select a digest</h3>
        <p className="mt-2 text-sm text-slate-600">Choose a weekly digest card to read the full engineering summary.</p>
      </article>
    );
  }

  return (
    <article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <p className="text-xs uppercase tracking-[0.16em] text-slate-500">
        {new Date(digest.periodStart).toLocaleDateString()} - {new Date(digest.periodEnd).toLocaleDateString()}
      </p>
      <h3 className="mt-2 text-2xl font-semibold tracking-tight text-slate-900">{digest.title}</h3>
      <p className="mt-3 text-sm text-slate-600">{digest.summary}</p>
      <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4">
        <pre className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{digest.bodyMarkdown || "No digest body available."}</pre>
      </div>
      <p className="mt-4 text-xs text-slate-500">
        Generated by {digest.generatedBy} on {new Date(digest.createdAt).toLocaleString()}
      </p>
    </article>
  );
}
