// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID *uuid.UUID         `json:"organization_id"`
	ActorUserID    *uuid.UUID         `json:"actor_user_id"`
	Action         string             `json:"action"`
	EntityType     string             `json:"entity_type"`
	EntityID       *uuid.UUID         `json:"entity_id"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Digest struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	RepositoryID   uuid.UUID          `json:"repository_id"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `json:"period_end"`
	Title          string             `json:"title"`
	Summary        string             `json:"summary"`
	BodyMarkdown   string             `json:"body_markdown"`
	GeneratedBy    string             `json:"generated_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type GithubAccount struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	GithubUserID         int64              `json:"github_user_id"`
	GithubLogin          string             `json:"github_login"`
	AccessTokenEncrypted string             `json:"access_token_encrypted"`
	TokenScope           pgtype.Text        `json:"token_scope"`
	ConnectedAt          pgtype.Timestamptz `json:"connected_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Issue struct {
	ID                uuid.UUID          `json:"id"`
	RepositoryID      uuid.UUID          `json:"repository_id"`
	GithubIssueID     int64              `json:"github_issue_id"`
	GithubIssueNumber int32              `json:"github_issue_number"`
	Title             string             `json:"title"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	AuthorLogin       pgtype.Text        `json:"author_login"`
	HtmlUrl           string             `json:"html_url"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	Labels            []byte             `json:"labels"`
	CreatedAtExternal pgtype.Timestamptz `json:"created_at_external"`
	UpdatedAtExternal pgtype.Timestamptz `json:"updated_at_external"`
	SyncedAt          pgtype.Timestamptz `json:"synced_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Job struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID *uuid.UUID         `json:"organization_id"`
	RepositoryID   *uuid.UUID         `json:"repository_id"`
	JobType        string             `json:"job_type"`
	Status         string             `json:"status"`
	QueueName      pgtype.Text        `json:"queue_name"`
	Attempts       int32              `json:"attempts"`
	LastError      pgtype.Text        `json:"last_error"`
	Payload        []byte             `json:"payload"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Membership struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	UserID         uuid.UUID          `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MemoryEntry struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	RepositoryID   uuid.UUID          `json:"repository_id"`
	Type           string             `json:"type"`
	Title          string             `json:"title"`
	Summary        string             `json:"summary"`
	WhyItMatters   pgtype.Text        `json:"why_it_matters"`
	ImpactedAreas  []byte             `json:"impacted_areas"`
	Risks          []byte             `json:"risks"`
	FollowUps      []byte             `json:"follow_ups"`
	SourceKind     pgtype.Text        `json:"source_kind"`
	SourceID       *uuid.UUID         `json:"source_id"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	GeneratedBy    string             `json:"generated_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MemoryEntrySource struct {
	ID             uuid.UUID          `json:"id"`
	MemoryEntryID  uuid.UUID          `json:"memory_entry_id"`
	SourceType     string             `json:"source_type"`
	SourceRecordID uuid.UUID          `json:"source_record_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PullRequest struct {
	ID                uuid.UUID          `json:"id"`
	RepositoryID      uuid.UUID          `json:"repository_id"`
	GithubPrID        int64              `json:"github_pr_id"`
	GithubPrNumber    int32              `json:"github_pr_number"`
	Title             string             `json:"title"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	AuthorLogin       pgtype.Text        `json:"author_login"`
	HtmlUrl           string             `json:"html_url"`
	MergedAt          pgtype.Timestamptz `json:"merged_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	Labels            []byte             `json:"labels"`
	CreatedAtExternal pgtype.Timestamptz `json:"created_at_external"`
	UpdatedAtExternal pgtype.Timestamptz `json:"updated_at_external"`
	SyncedAt          pgtype.Timestamptz `json:"synced_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Repository struct {
	ID             uuid.UUID          `json:"id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	GithubRepoID   int64              `json:"github_repo_id"`
	OwnerLogin     string             `json:"owner_login"`
	Name           string             `json:"name"`
	FullName       string             `json:"full_name"`
	Private        bool               `json:"private"`
	DefaultBranch  string             `json:"default_branch"`
	HtmlUrl        string             `json:"html_url"`
	Description    pgtype.Text        `json:"description"`
	IsActive       bool               `json:"is_active"`
	ImportedAt     pgtype.Timestamptz `json:"imported_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RepositorySyncState struct {
	ID                   uuid.UUID          `json:"id"`
	RepositoryID         uuid.UUID          `json:"repository_id"`
	LastPrSyncAt         pgtype.Timestamptz `json:"last_pr_sync_at"`
	LastIssueSyncAt      pgtype.Timestamptz `json:"last_issue_sync_at"`
	LastSuccessfulSyncAt pgtype.Timestamptz `json:"last_successful_sync_at"`
	LastSyncStatus       pgtype.Text        `json:"last_sync_status"`
	LastSyncError        pgtype.Text        `json:"last_sync_error"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
