// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	GetLatestGithubAccountForUser(ctx context.Context, userID uuid.UUID) (GithubAccount, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationForUser(ctx context.Context, arg GetOrganizationForUserParams) (GetOrganizationForUserRow, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertDigest(ctx context.Context, arg InsertDigestParams) (Digest, error)
	InsertJob(ctx context.Context, arg InsertJobParams) (Job, error)
	InsertMemoryEntry(ctx context.Context, arg InsertMemoryEntryParams) (MemoryEntry, error)
	LinkMemoryEntrySource(ctx context.Context, arg LinkMemoryEntrySourceParams) (MemoryEntrySource, error)
	ListDigestsForRepository(ctx context.Context, repositoryID uuid.UUID) ([]Digest, error)
	ListMemoryEntriesForRepository(ctx context.Context, arg ListMemoryEntriesForRepositoryParams) ([]MemoryEntry, error)
	ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]Organization, error)
	ListOrganizationsWithRoleForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsWithRoleForUserRow, error)
	ListRepositoriesForOrganization(ctx context.Context, organizationID uuid.UUID) ([]Repository, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
	UpsertGithubAccount(ctx context.Context, arg UpsertGithubAccountParams) (GithubAccount, error)
	UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error)
	UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (PullRequest, error)
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error)
	UpsertRepositorySyncState(ctx context.Context, arg UpsertRepositorySyncStateParams) (RepositorySyncState, error)
	UpsertUserByID(ctx context.Context, arg UpsertUserByIDParams) (User, error)
	UserHasMembership(ctx context.Context, arg UserHasMembershipParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
