// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (
  organization_id,
  user_id,
  role
) VALUES (
  $1,
  $2,
  $3
)
RETURNING id, organization_id, user_id, role, created_at
`

type CreateMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.OrganizationID, arg.UserID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
  name,
  slug
) VALUES (
  $1,
  $2
)
RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestGithubAccountForUser = `-- name: GetLatestGithubAccountForUser :one
SELECT id, user_id, github_user_id, github_login, access_token_encrypted, token_scope, connected_at, created_at, updated_at
FROM github_accounts
WHERE user_id = $1
ORDER BY connected_at DESC
LIMIT 1
`

func (q *Queries) GetLatestGithubAccountForUser(ctx context.Context, userID uuid.UUID) (GithubAccount, error) {
	row := q.db.QueryRow(ctx, getLatestGithubAccountForUser, userID)
	var i GithubAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.AccessTokenEncrypted,
		&i.TokenScope,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, created_at, updated_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationForUser = `-- name: GetOrganizationForUser :one
SELECT
  o.id,
  o.name,
  o.slug,
  o.created_at,
  o.updated_at,
  m.role
FROM organizations o
INNER JOIN memberships m ON m.organization_id = o.id
WHERE o.id = $1 AND m.user_id = $2
`

type GetOrganizationForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetOrganizationForUserRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      string             `json:"role"`
}

func (q *Queries) GetOrganizationForUser(ctx context.Context, arg GetOrganizationForUserParams) (GetOrganizationForUserRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationForUser, arg.ID, arg.UserID)
	var i GetOrganizationForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_logs (
  organization_id,
  actor_user_id,
  action,
  entity_type,
  entity_id,
  metadata
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, organization_id, actor_user_id, action, entity_type, entity_id, metadata, created_at
`

type InsertAuditLogParams struct {
	OrganizationID *uuid.UUID `json:"organization_id"`
	ActorUserID    *uuid.UUID `json:"actor_user_id"`
	Action         string     `json:"action"`
	EntityType     string     `json:"entity_type"`
	EntityID       *uuid.UUID `json:"entity_id"`
	Metadata       []byte     `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.OrganizationID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertDigest = `-- name: InsertDigest :one
INSERT INTO digests (
  organization_id,
  repository_id,
  period_start,
  period_end,
  title,
  summary,
  body_markdown,
  generated_by,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  NOW()
)
RETURNING id, organization_id, repository_id, period_start, period_end, title, summary, body_markdown, generated_by, created_at, updated_at
`

type InsertDigestParams struct {
	OrganizationID uuid.UUID          `json:"organization_id"`
	RepositoryID   uuid.UUID          `json:"repository_id"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `json:"period_end"`
	Title          string             `json:"title"`
	Summary        string             `json:"summary"`
	BodyMarkdown   string             `json:"body_markdown"`
	GeneratedBy    string             `json:"generated_by"`
}

func (q *Queries) InsertDigest(ctx context.Context, arg InsertDigestParams) (Digest, error) {
	row := q.db.QueryRow(ctx, insertDigest,
		arg.OrganizationID,
		arg.RepositoryID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Title,
		arg.Summary,
		arg.BodyMarkdown,
		arg.GeneratedBy,
	)
	var i Digest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RepositoryID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Summary,
		&i.BodyMarkdown,
		&i.GeneratedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
  organization_id,
  repository_id,
  job_type,
  status,
  queue_name,
  attempts,
  last_error,
  payload,
  started_at,
  finished_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  NOW()
)
RETURNING id, organization_id, repository_id, job_type, status, queue_name, attempts, last_error, payload, started_at, finished_at, created_at, updated_at
`

type InsertJobParams struct {
	OrganizationID *uuid.UUID         `json:"organization_id"`
	RepositoryID   *uuid.UUID         `json:"repository_id"`
	JobType        string             `json:"job_type"`
	Status         string             `json:"status"`
	QueueName      pgtype.Text        `json:"queue_name"`
	Attempts       int32              `json:"attempts"`
	LastError      pgtype.Text        `json:"last_error"`
	Payload        []byte             `json:"payload"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, insertJob,
		arg.OrganizationID,
		arg.RepositoryID,
		arg.JobType,
		arg.Status,
		arg.QueueName,
		arg.Attempts,
		arg.LastError,
		arg.Payload,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RepositoryID,
		&i.JobType,
		&i.Status,
		&i.QueueName,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMemoryEntry = `-- name: InsertMemoryEntry :one
INSERT INTO memory_entries (
  organization_id,
  repository_id,
  type,
  title,
  summary,
  why_it_matters,
  impacted_areas,
  risks,
  follow_ups,
  source_kind,
  source_id,
  source_url,
  generated_by,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  NOW()
)
RETURNING id, organization_id, repository_id, type, title, summary, why_it_matters, impacted_areas, risks, follow_ups, source_kind, source_id, source_url, generated_by, created_at, updated_at
`

type InsertMemoryEntryParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	RepositoryID   uuid.UUID   `json:"repository_id"`
	Type           string      `json:"type"`
	Title          string      `json:"title"`
	Summary        string      `json:"summary"`
	WhyItMatters   pgtype.Text `json:"why_it_matters"`
	ImpactedAreas  []byte      `json:"impacted_areas"`
	Risks          []byte      `json:"risks"`
	FollowUps      []byte      `json:"follow_ups"`
	SourceKind     pgtype.Text `json:"source_kind"`
	SourceID       *uuid.UUID  `json:"source_id"`
	SourceUrl      pgtype.Text `json:"source_url"`
	GeneratedBy    string      `json:"generated_by"`
}

func (q *Queries) InsertMemoryEntry(ctx context.Context, arg InsertMemoryEntryParams) (MemoryEntry, error) {
	row := q.db.QueryRow(ctx, insertMemoryEntry,
		arg.OrganizationID,
		arg.RepositoryID,
		arg.Type,
		arg.Title,
		arg.Summary,
		arg.WhyItMatters,
		arg.ImpactedAreas,
		arg.Risks,
		arg.FollowUps,
		arg.SourceKind,
		arg.SourceID,
		arg.SourceUrl,
		arg.GeneratedBy,
	)
	var i MemoryEntry
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RepositoryID,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.WhyItMatters,
		&i.ImpactedAreas,
		&i.Risks,
		&i.FollowUps,
		&i.SourceKind,
		&i.SourceID,
		&i.SourceUrl,
		&i.GeneratedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkMemoryEntrySource = `-- name: LinkMemoryEntrySource :one
INSERT INTO memory_entry_sources (
  memory_entry_id,
  source_type,
  source_record_id
) VALUES (
  $1,
  $2,
  $3
)
ON CONFLICT (memory_entry_id, source_type, source_record_id)
DO UPDATE SET source_record_id = EXCLUDED.source_record_id
RETURNING id, memory_entry_id, source_type, source_record_id, created_at
`

type LinkMemoryEntrySourceParams struct {
	MemoryEntryID  uuid.UUID `json:"memory_entry_id"`
	SourceType     string    `json:"source_type"`
	SourceRecordID uuid.UUID `json:"source_record_id"`
}

func (q *Queries) LinkMemoryEntrySource(ctx context.Context, arg LinkMemoryEntrySourceParams) (MemoryEntrySource, error) {
	row := q.db.QueryRow(ctx, linkMemoryEntrySource, arg.MemoryEntryID, arg.SourceType, arg.SourceRecordID)
	var i MemoryEntrySource
	err := row.Scan(
		&i.ID,
		&i.MemoryEntryID,
		&i.SourceType,
		&i.SourceRecordID,
		&i.CreatedAt,
	)
	return i, err
}

const listDigestsForRepository = `-- name: ListDigestsForRepository :many
SELECT id, organization_id, repository_id, period_start, period_end, title, summary, body_markdown, generated_by, created_at, updated_at
FROM digests
WHERE repository_id = $1
ORDER BY period_start DESC
`

func (q *Queries) ListDigestsForRepository(ctx context.Context, repositoryID uuid.UUID) ([]Digest, error) {
	rows, err := q.db.Query(ctx, listDigestsForRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Digest{}
	for rows.Next() {
		var i Digest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RepositoryID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Title,
			&i.Summary,
			&i.BodyMarkdown,
			&i.GeneratedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryEntriesForRepository = `-- name: ListMemoryEntriesForRepository :many
SELECT id, organization_id, repository_id, type, title, summary, why_it_matters, impacted_areas, risks, follow_ups, source_kind, source_id, source_url, generated_by, created_at, updated_at
FROM memory_entries
WHERE repository_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMemoryEntriesForRepositoryParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListMemoryEntriesForRepository(ctx context.Context, arg ListMemoryEntriesForRepositoryParams) ([]MemoryEntry, error) {
	rows, err := q.db.Query(ctx, listMemoryEntriesForRepository, arg.RepositoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryEntry{}
	for rows.Next() {
		var i MemoryEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.RepositoryID,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.WhyItMatters,
			&i.ImpactedAreas,
			&i.Risks,
			&i.FollowUps,
			&i.SourceKind,
			&i.SourceID,
			&i.SourceUrl,
			&i.GeneratedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at
FROM organizations o
INNER JOIN memberships m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at DESC
`

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsWithRoleForUser = `-- name: ListOrganizationsWithRoleForUser :many
SELECT
  o.id,
  o.name,
  o.slug,
  o.created_at,
  o.updated_at,
  m.role
FROM organizations o
INNER JOIN memberships m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at DESC
`

type ListOrganizationsWithRoleForUserRow struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      string             `json:"role"`
}

func (q *Queries) ListOrganizationsWithRoleForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsWithRoleForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsWithRoleForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsWithRoleForUserRow{}
	for rows.Next() {
		var i ListOrganizationsWithRoleForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesForOrganization = `-- name: ListRepositoriesForOrganization :many
SELECT id, organization_id, github_repo_id, owner_login, name, full_name, private, default_branch, html_url, description, is_active, imported_at, created_at, updated_at
FROM repositories
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRepositoriesForOrganization(ctx context.Context, organizationID uuid.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.GithubRepoID,
			&i.OwnerLogin,
			&i.Name,
			&i.FullName,
			&i.Private,
			&i.DefaultBranch,
			&i.HtmlUrl,
			&i.Description,
			&i.IsActive,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET
  status = $2,
  attempts = $3,
  last_error = $4,
  started_at = $5,
  finished_at = $6,
  updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, repository_id, job_type, status, queue_name, attempts, last_error, payload, started_at, finished_at, created_at, updated_at
`

type UpdateJobStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	Attempts   int32              `json:"attempts"`
	LastError  pgtype.Text        `json:"last_error"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.Attempts,
		arg.LastError,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.RepositoryID,
		&i.JobType,
		&i.Status,
		&i.QueueName,
		&i.Attempts,
		&i.LastError,
		&i.Payload,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGithubAccount = `-- name: UpsertGithubAccount :one
INSERT INTO github_accounts (
  user_id,
  github_user_id,
  github_login,
  access_token_encrypted,
  token_scope,
  connected_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  NOW(),
  NOW()
)
ON CONFLICT (user_id, github_user_id)
DO UPDATE SET
  github_login = EXCLUDED.github_login,
  access_token_encrypted = EXCLUDED.access_token_encrypted,
  token_scope = EXCLUDED.token_scope,
  connected_at = NOW(),
  updated_at = NOW()
RETURNING id, user_id, github_user_id, github_login, access_token_encrypted, token_scope, connected_at, created_at, updated_at
`

type UpsertGithubAccountParams struct {
	UserID               uuid.UUID   `json:"user_id"`
	GithubUserID         int64       `json:"github_user_id"`
	GithubLogin          string      `json:"github_login"`
	AccessTokenEncrypted string      `json:"access_token_encrypted"`
	TokenScope           pgtype.Text `json:"token_scope"`
}

func (q *Queries) UpsertGithubAccount(ctx context.Context, arg UpsertGithubAccountParams) (GithubAccount, error) {
	row := q.db.QueryRow(ctx, upsertGithubAccount,
		arg.UserID,
		arg.GithubUserID,
		arg.GithubLogin,
		arg.AccessTokenEncrypted,
		arg.TokenScope,
	)
	var i GithubAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.AccessTokenEncrypted,
		&i.TokenScope,
		&i.ConnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIssue = `-- name: UpsertIssue :one
INSERT INTO issues (
  repository_id,
  github_issue_id,
  github_issue_number,
  title,
  body,
  state,
  author_login,
  html_url,
  closed_at,
  labels,
  created_at_external,
  updated_at_external,
  synced_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  NOW(),
  NOW()
)
ON CONFLICT (repository_id, github_issue_id)
DO UPDATE SET
  github_issue_number = EXCLUDED.github_issue_number,
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  state = EXCLUDED.state,
  author_login = EXCLUDED.author_login,
  html_url = EXCLUDED.html_url,
  closed_at = EXCLUDED.closed_at,
  labels = EXCLUDED.labels,
  created_at_external = EXCLUDED.created_at_external,
  updated_at_external = EXCLUDED.updated_at_external,
  synced_at = NOW(),
  updated_at = NOW()
RETURNING id, repository_id, github_issue_id, github_issue_number, title, body, state, author_login, html_url, closed_at, labels, created_at_external, updated_at_external, synced_at, created_at, updated_at
`

type UpsertIssueParams struct {
	RepositoryID      uuid.UUID          `json:"repository_id"`
	GithubIssueID     int64              `json:"github_issue_id"`
	GithubIssueNumber int32              `json:"github_issue_number"`
	Title             string             `json:"title"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	AuthorLogin       pgtype.Text        `json:"author_login"`
	HtmlUrl           string             `json:"html_url"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	Labels            []byte             `json:"labels"`
	CreatedAtExternal pgtype.Timestamptz `json:"created_at_external"`
	UpdatedAtExternal pgtype.Timestamptz `json:"updated_at_external"`
}

func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, upsertIssue,
		arg.RepositoryID,
		arg.GithubIssueID,
		arg.GithubIssueNumber,
		arg.Title,
		arg.Body,
		arg.State,
		arg.AuthorLogin,
		arg.HtmlUrl,
		arg.ClosedAt,
		arg.Labels,
		arg.CreatedAtExternal,
		arg.UpdatedAtExternal,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GithubIssueID,
		&i.GithubIssueNumber,
		&i.Title,
		&i.Body,
		&i.State,
		&i.AuthorLogin,
		&i.HtmlUrl,
		&i.ClosedAt,
		&i.Labels,
		&i.CreatedAtExternal,
		&i.UpdatedAtExternal,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPullRequest = `-- name: UpsertPullRequest :one
INSERT INTO pull_requests (
  repository_id,
  github_pr_id,
  github_pr_number,
  title,
  body,
  state,
  author_login,
  html_url,
  merged_at,
  closed_at,
  labels,
  created_at_external,
  updated_at_external,
  synced_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  NOW(),
  NOW()
)
ON CONFLICT (repository_id, github_pr_id)
DO UPDATE SET
  github_pr_number = EXCLUDED.github_pr_number,
  title = EXCLUDED.title,
  body = EXCLUDED.body,
  state = EXCLUDED.state,
  author_login = EXCLUDED.author_login,
  html_url = EXCLUDED.html_url,
  merged_at = EXCLUDED.merged_at,
  closed_at = EXCLUDED.closed_at,
  labels = EXCLUDED.labels,
  created_at_external = EXCLUDED.created_at_external,
  updated_at_external = EXCLUDED.updated_at_external,
  synced_at = NOW(),
  updated_at = NOW()
RETURNING id, repository_id, github_pr_id, github_pr_number, title, body, state, author_login, html_url, merged_at, closed_at, labels, created_at_external, updated_at_external, synced_at, created_at, updated_at
`

type UpsertPullRequestParams struct {
	RepositoryID      uuid.UUID          `json:"repository_id"`
	GithubPrID        int64              `json:"github_pr_id"`
	GithubPrNumber    int32              `json:"github_pr_number"`
	Title             string             `json:"title"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	AuthorLogin       pgtype.Text        `json:"author_login"`
	HtmlUrl           string             `json:"html_url"`
	MergedAt          pgtype.Timestamptz `json:"merged_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	Labels            []byte             `json:"labels"`
	CreatedAtExternal pgtype.Timestamptz `json:"created_at_external"`
	UpdatedAtExternal pgtype.Timestamptz `json:"updated_at_external"`
}

func (q *Queries) UpsertPullRequest(ctx context.Context, arg UpsertPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, upsertPullRequest,
		arg.RepositoryID,
		arg.GithubPrID,
		arg.GithubPrNumber,
		arg.Title,
		arg.Body,
		arg.State,
		arg.AuthorLogin,
		arg.HtmlUrl,
		arg.MergedAt,
		arg.ClosedAt,
		arg.Labels,
		arg.CreatedAtExternal,
		arg.UpdatedAtExternal,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.GithubPrID,
		&i.GithubPrNumber,
		&i.Title,
		&i.Body,
		&i.State,
		&i.AuthorLogin,
		&i.HtmlUrl,
		&i.MergedAt,
		&i.ClosedAt,
		&i.Labels,
		&i.CreatedAtExternal,
		&i.UpdatedAtExternal,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (
  organization_id,
  github_repo_id,
  owner_login,
  name,
  full_name,
  private,
  default_branch,
  html_url,
  description,
  is_active,
  imported_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  NOW(),
  NOW()
)
ON CONFLICT (organization_id, github_repo_id)
DO UPDATE SET
  owner_login = EXCLUDED.owner_login,
  name = EXCLUDED.name,
  full_name = EXCLUDED.full_name,
  private = EXCLUDED.private,
  default_branch = EXCLUDED.default_branch,
  html_url = EXCLUDED.html_url,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  updated_at = NOW()
RETURNING id, organization_id, github_repo_id, owner_login, name, full_name, private, default_branch, html_url, description, is_active, imported_at, created_at, updated_at
`

type UpsertRepositoryParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	GithubRepoID   int64       `json:"github_repo_id"`
	OwnerLogin     string      `json:"owner_login"`
	Name           string      `json:"name"`
	FullName       string      `json:"full_name"`
	Private        bool        `json:"private"`
	DefaultBranch  string      `json:"default_branch"`
	HtmlUrl        string      `json:"html_url"`
	Description    pgtype.Text `json:"description"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, upsertRepository,
		arg.OrganizationID,
		arg.GithubRepoID,
		arg.OwnerLogin,
		arg.Name,
		arg.FullName,
		arg.Private,
		arg.DefaultBranch,
		arg.HtmlUrl,
		arg.Description,
		arg.IsActive,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.GithubRepoID,
		&i.OwnerLogin,
		&i.Name,
		&i.FullName,
		&i.Private,
		&i.DefaultBranch,
		&i.HtmlUrl,
		&i.Description,
		&i.IsActive,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepositorySyncState = `-- name: UpsertRepositorySyncState :one
INSERT INTO repository_sync_states (
  repository_id,
  last_pr_sync_at,
  last_issue_sync_at,
  last_successful_sync_at,
  last_sync_status,
  last_sync_error,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  NOW()
)
ON CONFLICT (repository_id)
DO UPDATE SET
  last_pr_sync_at = EXCLUDED.last_pr_sync_at,
  last_issue_sync_at = EXCLUDED.last_issue_sync_at,
  last_successful_sync_at = EXCLUDED.last_successful_sync_at,
  last_sync_status = EXCLUDED.last_sync_status,
  last_sync_error = EXCLUDED.last_sync_error,
  updated_at = NOW()
RETURNING id, repository_id, last_pr_sync_at, last_issue_sync_at, last_successful_sync_at, last_sync_status, last_sync_error, created_at, updated_at
`

type UpsertRepositorySyncStateParams struct {
	RepositoryID         uuid.UUID          `json:"repository_id"`
	LastPrSyncAt         pgtype.Timestamptz `json:"last_pr_sync_at"`
	LastIssueSyncAt      pgtype.Timestamptz `json:"last_issue_sync_at"`
	LastSuccessfulSyncAt pgtype.Timestamptz `json:"last_successful_sync_at"`
	LastSyncStatus       pgtype.Text        `json:"last_sync_status"`
	LastSyncError        pgtype.Text        `json:"last_sync_error"`
}

func (q *Queries) UpsertRepositorySyncState(ctx context.Context, arg UpsertRepositorySyncStateParams) (RepositorySyncState, error) {
	row := q.db.QueryRow(ctx, upsertRepositorySyncState,
		arg.RepositoryID,
		arg.LastPrSyncAt,
		arg.LastIssueSyncAt,
		arg.LastSuccessfulSyncAt,
		arg.LastSyncStatus,
		arg.LastSyncError,
	)
	var i RepositorySyncState
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.LastPrSyncAt,
		&i.LastIssueSyncAt,
		&i.LastSuccessfulSyncAt,
		&i.LastSyncStatus,
		&i.LastSyncError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByID = `-- name: UpsertUserByID :one
INSERT INTO users (
  id,
  email,
  display_name,
  avatar_url,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  NOW()
)
ON CONFLICT (id)
DO UPDATE SET
  email = COALESCE(EXCLUDED.email, users.email),
  display_name = COALESCE(NULLIF(EXCLUDED.display_name, ''), users.display_name),
  avatar_url = COALESCE(EXCLUDED.avatar_url, users.avatar_url),
  updated_at = NOW()
RETURNING id, email, display_name, avatar_url, created_at, updated_at
`

type UpsertUserByIDParams struct {
	ID          uuid.UUID   `json:"id"`
	Email       pgtype.Text `json:"email"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUserByID(ctx context.Context, arg UpsertUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByID,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userHasMembership = `-- name: UserHasMembership :one
SELECT EXISTS(
  SELECT 1
  FROM memberships
  WHERE user_id = $1 AND organization_id = $2
)
`

type UserHasMembershipParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) UserHasMembership(ctx context.Context, arg UserHasMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasMembership, arg.UserID, arg.OrganizationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
